apiVersion: skaffold/v2beta13
kind: Config
deploy: 
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
#  local:
#    push: false
  googleCloudBuild:
    projectId: ticketing-dev-309920
  artifacts: 
    - image: us.gcr.io/ticketing-dev-309920/auth
      context: auth
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .